### ISSUE TITLE
Hackathon submission checklist

### ISSUE THREAD

**Issue by dankelleher** [sunrise-stake/app#30]
UI/UX

- [ ]  #17 UI redesign complete
- [x] #29 Fee calculator integrated

Functionality 
- [x] #2 Feeless liquid unstake
- [ ] #22 SolBlaze integrated
- [x] #10 Tweet button on deposit
- [x] #12 Token metadata updated
- [x] #16 controller program initial version

Devops
- [x] mainnet sunrise program updated
- [x] mainnet sunrise-state updated
- [x] mainnet lp token account created
- [x] mainnet sunrise account rebalanced
- [x] mainnet controller program deployed
- [x] mainnet controller config set
- [x] sunrise treasury set to controller PDA
- [x] delegate set on NCT holding account to controller PDA
- [x] SOL/NCT price calculated and set

Submission
- [x] Doc text  updated
- [x] Finalise voice-over script
- [x] Slides with animated diagrams [MK] 15h UTC
- [x] Record how-to guide (UI walkthrough)
- [x] Record voice-over [EO] 17h UTC
- [x] Sunrise Stake Youtube channel [DK] 19h UTC
- [x] Compile diagrams, voice over, walkthrough and edit [EO] 20h UTC
- [x] Short project description and description per track [DK] 17h UTC
- [x] Twitter post [DK] 20h UTC
- [x] Wallet addresses, discord handles of the team. [DK] 19h UTC
- [x] Actually submit the application [EO] 21h UTC (22h CET)
- [x] Doc diagrams added (aim for 50/50 diagrams & text) [DK] 14h UTC
- [x] "Get out the vote" campaign to get people to 👍 our application (tuesday)
- [x] Twitter space (optional) (tuesday)

**Comment by Mjavala** [comment]
@dankelleher awaiting review of the treasury controller, standing by until then
